### ISSUE TITLE
Accessing QRadar 

### ISSUE THREAD

**Issue by meherzad-j** [ibm-security-intelligence/api-samples#13]
Can somebody guide me how will i pass my username password to QRadar through APIs to access it.?

**Comment by ghost** [comment]
The samples here have examples that do this via base64 encoded Basic Authentication
This line specifically
https://github.com/ibm-security-intelligence/api-samples/blob/master/modules/RestApiClient.py#L39 and assumes you are using python.

The API guide describes the different ways to authenticate as well link below to the 7.3 version of them
http://public.dhe.ibm.com/software/security/products/qradar/documents/7.3.0/en/b_qradar_api.pdf
