### ISSUE TITLE
Not following PEP8 for Python Code

### ISSUE THREAD

**Issue by RyPeck** [ibm-security-intelligence/api-samples#4]
Not sure if you guys are following an IBM spec for Python code - but generally people try to follow pep8.

https://www.python.org/dev/peps/pep-0008/
https://pypi.python.org/pypi/pep8

My biggest problem is the tabs. My editor settings expect spaces.

**Comment by davidgpayne** [comment]
The 7.2.4 and master branches have been updated to pass pep8 tests.
