### ISSUE TITLE
Update Asset Operating System

### ISSUE THREAD

**Issue by makefu** [ibm-security-intelligence/api-samples#8]
Hi,

i am looking for a way to set the operating system for an asset via the api.
I have an input with OS Strings like: `LINUX SuSE Enterprise Server 11 64bit` or `Windows 2008 Standard R2 x64`.
The first question is how can i retrieve the list of available operating systems,
the second is if there is a way to fuzzy-search the list or to simply override the OS name.

**Comment by ghost** [comment]
Closing
